{% set name = "rubicon-ml" %}
{% set version = "0.15.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b9027b004cd7fa39b612930b0683af9333ae284d7bddafe957ac028982398d15

build:
  number: 0
  noarch: python
  entry_points:
    - rubicon_ml=rubicon_ml.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click <=8.4.1,>=7.1
    - dash <=2.18.2,>=2.0.0
    - dash-bootstrap-components <=1.7.1,>=1.0.0
    - fsspec <=2026.6.0,>=2021.4.0
    - intake <=2.0.9,>=0.5.2
    - jsonpath-ng <=1.8.0,>=1.5.3
    - numpy <=2.5.0,>=1.22.0
    - pandas <=3.0.3,>=1.0
    - pyarrow <=24.0.0,>=14.0.1
    - python >={{ python_min }}
    - pyyaml <=6.0.3,>=5.4.0
    - s3fs <=2026.6.0,>=0.4
    - scikit-learn <=1.9.0,>=0.22.0

test:
  imports:
    - rubicon_ml
  commands:
    - rubicon_ml --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/capitalone/rubicon-ml
  doc_url: https://capitalone.github.io/rubicon-ml/
  summary: library and CLI for standardizing model development and governance
  license: Apache-2.0
  license_file: LICENSE
  description: |
    rubicon-ml is a machine learning solution designed to help standardize the model 
    development lifecycle. rubicon-ml can track, visualize and share experiments with 
    collaborators and reviewers as they develop, train and govern models designed 
    to solve complex business problems. It simplifies model governance, auditability 
    and reproducibility by tracking a wide range of model metadata.

extra:
  recipe-maintainers:
    - joe-wolfe21
    - ryanSoley
    - mmccarty
    - dianelee217
